### ISSUE TITLE
Mapnik installation fails because of dependencies

### ISSUE THREAD

**Issue by Sachithj22** [mapnik/mapnik-support#100]
I've tried installing mapnik in my ubuntu 14.04 VM. but it always fails to install due to below reason.
(cached) Searching for boost libs and headers... (cached)
  *libs found: /usr/lib
  *headers found: /usr/include
  *lib naming extension found: .so.1.49
Checking for Boost version >= 1.41... yes
Found boost lib version... 1_54
Checking for C++ library boost_system.so.1.49... no
Could not find required header or shared library for boost system
Checking for C++ library boost_filesystem.so.1.49... no
Could not find required header or shared library for boost filesystem
Checking for C++ library boost_regex.so.1.49... no
Could not find required header or shared library for boost regex
Checking for C++ library boost_program_options.so.1.49... no
Could not find optional header or shared library for boost program_options
Checking for C++ library boost_thread.so.1.49... no
Could not find required header or shared library for boost thread
Checking if boost_regex was built with ICU unicode support... (cached) no

But I've already installed :
intucell@sonbu-34:/intucell/osm/mapnik$ dpkg -s libboost-filesystem-dev
Package: libboost-filesystem-dev
Status: install ok installed
Priority: optional
Section: libdevel
Installed-Size: 26
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: boost-defaults
Version: 1.54.0.1ubuntu1
Depends: libboost-filesystem1.54-dev
Description: filesystem operations (portable paths, iteration over directories, etc) in C++ (default version)
 This package forms part of the Boost C++ Libraries collection.
 .
 The Boost Filesystem Library provides portable facilities to query and
 manipulate paths, files, and directories.  The goal is to
 facilitate portable script-like operations from within C++ programs.
 .
 This package is a dependency package, which depends on Debian's default
 Boost version (currently 1.54).
Homepage: http://boost.org/libs/filesystem/
Original-Maintainer: Debian Boost Team <pkg-boost-devel@lists.alioth.debian.org>

**Comment by springmeyer** [comment]
Look inside the `config.log` (that is produced after configure in your working directory). It has more details on why things failed to be found (like boost).

**Comment by Sachithj22** [comment]
Hi springmeye, I see below information in config.log file

g++ -o .sconf_temp/conftest_13.o -c -DHAVE_JPEG -Iinclude -I. -I/usr/local/include -I/usr/include -I/usr/include/freetype2 -I/usr/include/libxml2 .sconf_temp/conftest_13.cpp
g++ -o .sconf_temp/conftest_13 .sconf_temp/conftest_13.o -Lsrc -L/usr/local/lib -L/usr/lib -L/usr/lib/x86_64-linux-gnu -lfreetype -lz -lpng12 -lxml2 -lm -lltdl -lpng -ltiff -lz -lproj -licuuc -ljpeg -lboost_system.so.1.49
/usr/bin/ld: cannot find -lboost_system.so.1.49
collect2: error: ld returned 1 exit status
scons: Configure: no

I'm new to this. Could you please help? Does it mean that it is checking for boot v1.49 but I have v1.54 installed in the system?

**Comment by springmeyer** [comment]
@Sachithj22 yes it likely indicates that you have broken/conflicting installs of boost. What is happening is that the build is discovering that you have `/usr/lib/libboost_system.so.1.49` on your system, but the compiler/linker cannot find it. Perhaps `/usr/lib/libboost_system.so.1.49` is a broken symlink?

**Comment by Sachithj22** [comment]
@springmeyer 
libboost_system.so.1.49 is present under /usr/lib
-rw-r--r--   1 root root        70720 Feb  4  2013 libboost_date_time.so.1.49.0
-rw-r--r--   1 root root       132448 Feb  4  2013 libboost_filesystem.so.1.49.0
-rw-r--r--   1 root root       414608 Feb  4  2013 libboost_program_options.so.1.49.0
-rw-r--r--   1 root root       324640 Feb  4  2013 libboost_python-py26.so.1.49.0
-rw-r--r--   1 root root       324640 Feb  4  2013 libboost_python-py27.so.1.49.0
-rw-r--r--   1 root root       320480 Feb  4  2013 libboost_python-py32.so.1.49.0
-rw-r--r--   1 root root      1218208 Feb  4  2013 libboost_regex.so.1.49.0
-rw-r--r--   1 root root       517664 Feb  4  2013 libboost_serialization.so.1.49.0
-rw-r--r--   1 root root        13512 Feb  4  2013 libboost_system.so.1.49.0
-rw-r--r--   1 root root       120664 Feb  4  2013 libboost_thread.so.1.49.0

It is confusing that it showed v1.54 when I tried installing mapnik

**Comment by Sachithj22** [comment]
@springmeyer 
I was able solve the above issue by uninstalling all the libboost packages and  again installed it individually. But When I try to install Mapnik, I get below issue,

Notice: dependencies not met for plugin 'ogr', not building...
Notice: dependencies not met for plugin 'occi', not building...
Notice: dependencies not met for plugin 'rasterlite', not building...
Notice: dependencies not met for plugin 'gdal', not building...

**Comment by springmeyer** [comment]
@Sachithj22 - that is great news that the boost issue is resolved and it was a duplicate install problem. 

```
Notice: dependencies not met for plugin 'ogr', not building...
Notice: dependencies not met for plugin 'occi', not building...
Notice: dependencies not met for plugin 'rasterlite', not building...
Notice: dependencies not met for plugin 'gdal', not building...
```

That is just a warning and does not prevent the use of Mapnik. Those are mapnik plugins that have additional dependencies. Also, it looks like you are using an old Mapnik version. I recommend using at least v3.0.x (the latest release if v3.0.17).

**Comment by Sachithj22** [comment]
Thanks @springmeyer But I get below error message while importing mapnik in python,

Python 2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mapnik/__init__.py", line 46, in <module>
    from _mapnik import *
ImportError: /usr/local/lib/libmapnik.so.2.0: undefined symbol: _ZNK5boost9re_detail31icu_regex_traits_implementation12do_transformEPKiS3_PKN6icu_488CollatorE

Update: I tried to install the newer version of mapnik by below step:
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo apt-get update -y
sudo apt-get install -y gcc-6 g++-6 clang-3.8
export CXX="clang++-3.8" && export CC="clang-3.8" # <- define versions
git clone https://github.com/mapnik/mapnik --depth 10
cd mapnik
git submodule update --init
sudo apt-get install python zlib1g-dev clang make pkg-config curl
source bootstrap.sh
./configure CUSTOM_CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" CXX=${CXX} CC=${CC} # <- pass versions
make
make test
sudo make install

But now I encountered below new issue,
Python 2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mapnik
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mapnik/__init__.py", line 46, in <module>
    from _mapnik import *
ImportError: libmapnik.so.2.0: cannot open shared object file: No such file or directory

**Comment by springmeyer** [comment]
```
$ echo '_ZNK5boost9re_detail31icu_regex_traits_implementation12do_transformEPKiS3_PKN6icu_488CollatorE' | c++filt -n
boost::re_detail::icu_regex_traits_implementation::do_transform(int const*, int const*, icu_48::Collator const*) cons
```

So that indicates that python-mapnik is looking for ICU 48. Perhaps you have build mapnik against a different ICU version?

**Comment by springmeyer** [comment]
> ImportError: /usr/local/lib/libmapnik.so.2.0: undefined symbol: 

Also ^^ indicates that you have Mapnik 2.x on your system. I recommended above that you use Mapnik 3.x. I think you must have lots of duplicate libraries around from failed installs. Perhaps try cleaning up first before continuing?

**Comment by Sachithj22** [comment]
@springmeyer thanks for the help. Now I'm able to install mapnik

**Comment by Sachithj22** [comment]
Hi @springmeyer Now when I tried to install mod_tile I get following error message,

compilation terminated.
make[1]: *** [src/gen_tile_test-gen_tile_test.o] Error 1
make[1]: Leaving directory `/intucell/osm/mod_tile'
make: *** [all-recursive] Error 1
intucell@sonbu-38:/intucell/osm/mod_tile$ sudo make
Making all in iniparser3.0b
make[1]: Entering directory `/intucell/osm/mod_tile/iniparser3.0b'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/intucell/osm/mod_tile/iniparser3.0b'
make[1]: Entering directory `/intucell/osm/mod_tile'
g++ -DHAVE_CONFIG_H -I. -I./includes  -pthread -DSYSTEM_LIBINIPARSER=0  -I/usr/local/include -I/usr/local/include/mapnik/agg -I/usr/local/include/mapnik -I/intucell/osm/mapnik/mason_packages/.link/include -I/intucell/osm/mapnik/mason_packages/.link/include/freetype2 -I/intucell/osm/mapnik/mason_packages/.link/include/libpng16 -I/intucell/osm/mapnik/mason_packages/linux-x86_64/libgdal/2.1.3/include -I/intucell/osm/mapnik/mason_packages/.link/include/cairo -I/intucell/osm/mapnik/mason_packages/.link/include/pixman-1 -DMAPNIK_MEMORY_MAPPED_FILE -DMAPNIK_HAS_DLCFN -DBIGINT -DBOOST_REGEX_HAS_ICU -DHAVE_JPEG -DMAPNIK_USE_PROJ4 -DHAVE_PNG -DHAVE_WEBP -DHAVE_TIFF -DLINUX -DMAPNIK_THREADSAFE -DBOOST_SPIRIT_NO_PREDEFINED_TERMINALS=1 -DBOOST_PHOENIX_NO_PREDEFINED_TERMINALS=1 -DBOOST_SPIRIT_USE_PHOENIX_V3=1 -DNDEBUG -DHAVE_CAIRO -DGRID_RENDERER -DSVG_RENDERER -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -pthread -ftemplate-depth-300 -Wsign-compare -O3 -g -O2 -MT src/gen_tile_test-gen_tile_test.o -MD -MP -MF src/.deps/gen_tile_test-gen_tile_test.Tpo -c -o src/gen_tile_test-gen_tile_test.o `test -f 'src/gen_tile_test.cpp' || echo './'`src/gen_tile_test.cpp
src/gen_tile_test.cpp:58:28: fatal error: mapnik/box2d.hpp: No such file or directory
 #include <mapnik/box2d.hpp>
                            ^
compilation terminated.
make[1]: *** [src/gen_tile_test-gen_tile_test.o] Error 1
make[1]: Leaving directory `/intucell/osm/mod_tile'
make: *** [all-recursive] Error 1

mapnik-config --version
3.1.0
Could you please assist us?

**Comment by springmeyer** [comment]
@Sachithj22 - apologies. Looks like you downloaded Mapnik `master` from github. The `master` branch is going to be Mapnik 3.1.x, which has incompatible changes to header locations (e.g. `mapnik/box2d.hpp`  ->  `mapnik/geometry/box2d.hpp`) /cc @artemp 

I recommend using Mapnik 3.0.17 release instead of Master.

**Comment by totalspam** [comment]
> @springmeyer thanks for the help. Now I'm able to install mapnik

Hi! And how you made it? I have the same issue
