### ISSUE TITLE
Tests broken on 2.1.x

### ISSUE THREAD

**Issue by lexman** [mapnik/mapnik-support#5]
Hello,

have you noticed that tests are broken on branch 2.1.x ?

Implicit conversion of float to strings in filters tags won't work any more, on Ubuntu 12.04-LTS : 

``` shell

*** Running visual tests...
*** Running C++ tests...
tests/cpp_tests/conversions_test.cpp(68): test 'out == "0.0001234567890123456"' failed in function 'int main(int, char**)': '0.0001234567890123' != '0.0001234567890123456'
tests/cpp_tests/conversions_test.cpp(72): test 'out == "-0.0001234567890123456"' failed in function 'int main(int, char**)': '-0.0001234567890123' != '-0.0001234567890123456'
2 errors detected.
C++ CSV parse: ✓ 
C++ exceptions: ✓ 
C++ fonts registration: ✓ 
C++ label algorithms: ✓ 
C++ parameters: ✓ 
*** Running python tests...
Notice: skipping postgis tests (connection)
..........................................................T............F..........TT.......................................................................................................F.................................................................................................................................................................................................................................................T.......................
======================================================================
FAIL: python_tests.filter_test.test_float_precision
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lexman/dev/mapnik-tmp14/cdm_opensource_mapnik/tests/python_tests/filter_test.py", line 177, in test_float_precision
    eq_(expr.evaluate(f),True)
  File "/usr/local/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: False != True

======================================================================
FAIL: python_tests.object_test.test_shield_symbolizer_modify
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/lexman/dev/mapnik-tmp14/cdm_opensource_mapnik/tests/python_tests/object_test.py", line 173, in test_shield_symbolizer_modify
    check_transform("matrix(1 2 3 4 5 6)", "matrix(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)")
  File "/home/lexman/dev/mapnik-tmp14/cdm_opensource_mapnik/tests/python_tests/object_test.py", line 172, in check_transform
    eq_(s.transform, expr if expect_str is None else expect_str)
  File "/usr/local/lib/python2.7/dist-packages/nose/tools.py", line 31, in eq_
    assert a == b, msg or "%r != %r" % (a, b)
AssertionError: 'matrix(1, 2, 3, 4, 5, 6)' != 'matrix(1.0, 2.0, 3.0, 4.0, 5.0, 6.0)'

----------------------------------------------------------------------
Ran 453 tests in 8.892s

FAILED (TODO=4, failures=2)
make: *** [test] Error 1
```

**Comment by artemp** [comment]
@abonnasseau  - we'll need to fix tests, thanks.

**Comment by springmeyer** [comment]
@artemp - I noticed that we saw these same breakages in master, and that `test_float_precision` and `test_shield_symbolizer_modify` are no longer failing - you must have fixed these? Is another backport needed?

As far as the two `tests/cpp_tests/conversions_test.cpp` failures, I think @strk indicated these should be failing due to a boost::karma bug, so I figure we should just comment them in the 2.1.x branch. Thoughts?

**Comment by springmeyer** [comment]
tests are now fixed in the 2.1.x branch. @abonnasseau - can you update and let us know if they pass now for you?

**Comment by springmeyer** [comment]
btw, remaining loose ends tracked in mapnik/mapnik#1676

**Comment by lexman** [comment]
Tests pass now. Great !
